language: node_js
node_js:
 - "8"

before_install:
 - sudo apt-get -qq update
 - sudo apt-cache search chrome browser
 - sudo apt-get install chrome-browser
 - node -v
 - npm -v

install:
 - npm install -g karma-cli
 - npm install

script:
 - karma start